---

name: Build and push image

env:
  IMAGE: ghcr.io/helldweller/hecho
  NODE_VERSION: "20.5.1"

on:
  release:
    types: [ published ]
  workflow_dispatch:
    inputs:
      tag:
        required: true
        description: docker image tag

concurrency: 
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Setup QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Setup Docker Buildx local
        uses: docker/setup-buildx-action@v3
      -
        name: Login to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - 
        name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          flavor: |
            latest=false
          tags: |
            type=ref,event=tag
            type=sha,prefix=sha-,format=short
            ${{ inputs.tag != '' && format('type=raw,value={0}', inputs.tag) || '' }}
          images: ${{ env.IMAGE }}
      -
        name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          pull: true
          tags: ${{ steps.meta.outputs.tags }}
